import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StoreProvider from "./StoreProvider";
import Footer from "@/components/Footer";
import PostNav from "@/components/PostNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-screen font-poppins flex flex-col overflow-hidden`}
      >
        <StoreProvider>
          <Navbar />
          {/* Ensure children take remaining space & do not cause body scroll */}
          <div className="overflow-auto">
            {children}
            <Footer />
          </div>
          <div className="lg:hidden ">
            <PostNav />
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
